### ISSUE TITLE
possibly OF update broke the script

### ISSUE THREAD

**Issue by RonnieBlaze** [Amenly/onlyfans-scraper#10]
app is no longer working,, but neither is DIGITALCRIMINALs app.. so its probably something that OF has changed that is blocking both from logging in.

**Comment by Amenly** [comment]
Yep, they changed their authentication. I'll try to have an update out soon.

**Comment by Amenly** [comment]
Hmm, if I'm being honest, this one's a little tricky to figure out (unless there's something obvious that I'm missing). I think I have a general idea of how to fix the auth issues but I'm stumped on one specific part.

It sounds like DC has a fix that'll be released soon. I'm very interested to see how he solved it.

**Comment by Gixxa** [comment]
@Amenly 

Looks like it's been fixed:

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1078

**Comment by Amenly** [comment]
@Gixxa Yup I'm working on adding it to this repo right now

**Comment by Amenly** [comment]
I've updated the program to work with the new auth methods. It should work fine, you just need to include your x-bc token when you're setting up the program (I'll update the README with newer images).

If you're upgrading from an older version, I highly recommend deleting the old  `auth.json` file (in fact you might have to)! You can find it in your home folder. If you don't know where your home folder is, here's how you can find it:

Activate the Python interpreter by going to your terminal and simply type the following (don't include the dollar symbol):

```
$ python
```

or if you're on macOS/Linux:

```
$ python3
```

Then do the following commands (after each '>>>'):

```
>>> import pathlib
>>> pathlib.Path.home()
```

You should see the path to your home directory. Inside of it is a folder called `.config`. Inside of that is another one called `onlyfans-scraper`. Just search through it and you'll find it. Be aware that it might be in yet another folder called `main_profile` depending on which version you're upgrading from.

Oh, and remember, you need to delete the `auth.json` file. You might see another file called `config.json`. It doesn't matter if you delete the `config.json` file, another one will be made when you run the program. Just make sure you delete the `auth.json` file!

If you can't find your `.config` folder, it's because you have to enable the ability to view hidden folders (just Google "how to view hidden folders on <insert operating system here>").

=====

If you encounter ANY errors, *do not* hesitate to file an issue.

**Comment by mixan21** [comment]
Can i know how to update to the latest version? Is there a specific command or i just install again like the new from beginning?

**Comment by Amenly** [comment]
@mixan21 You can run the following in your terminal:

```
$ pip install --upgrade onlyfans-scraper
```

And if you're using macOS/Linux, replace `pip` with `pip3`

**Comment by mixan21** [comment]
> @mixan21 You can run the following in your terminal:
> 
> ```
> $ pip install --upgrade onlyfans-scraper
> ```
> 
> And if you're using macOS/Linux, replace `pip` with `pip3`
> 
> ===
> Edit:
> 
> If that doesn't work, try replacing `--upgrade` with `-U`
> 
> And don't forget to remove your `auth.json` file

@Amenly
The script works again after this new update. And the database still same which i don't have to do it again. Thank you so much for this update. My setting is parrot os virtual machine.
