### ISSUE TITLE
Status Code 400 after ~988 likes

### ISSUE THREAD

**Issue by Gixxa** [Amenly/onlyfans-scraper#13]
So i tried the "like function" and it worked perfect for one model (435 Posts at 0.5932 it/s).

After that I tried another model (2344 posts) and it worked great up until Post 554 at that point all I got was:

`400 STATUS CODE: unable to like post at *url of post*`

over and over. I tried the URL and it checks out, the post has not been liked. I can access it but not like it by hand.

I did use a VPN on the first model and the first 553 posts of model 2. I then deactivated the VPN and tried again with the same error only it now shows 0/1790 posts and 0.0 it/s.

Edit:

Unliking is the same - `400 STATUS CODE: unable to unlike post at *url of post*`

**Comment by Amenly** [comment]
Yeah the problem is that they recently put a limit on how many posts you can like in a day. If you go to your onlyfans account and try liking a post, the heart will probably turn blue but then revert back. It sounds like the daily limit is around 989 posts.

There's really nothing much I can do about this. But will I will update the error handling so that they give more info about what went wrong.

**Comment by Gixxa** [comment]
Ok thanks for the info. I'll test it at 00:01 to see if it's a day limit or 24h limit.

**Comment by Gixxa** [comment]
So a quick update before I close this:

It looks like OF locks you out for around 10-12 hours. I liked about 9xx posts yesterday at around 9:00 in the morning and was able to like again at around the same time in the evening.
