### ISSUE TITLE
403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by Brynting** [Amenly/onlyfans-scraper#6]
Getting this error when downloading most files. some files work fine tho. Didn't include the whole link.
403 Client Error: Forbidden for url: https://cdn2.onlyfans.com/files/

**Comment by Amenly** [comment]
So I had it happen to me before and I was able to find out which video it was. That same video (which was an old livestream) would not play on the website and would only give me a "The media could not be loaded, either because the server or network failed or because the format is not supported" message.

So I'm pretty sure this is just something on their end and there's not really much I can do about it. But I think it's odd that you're encountering it on most files but some work...that should be the other way around.

**Comment by Brynting** [comment]
the problem occurs with more than 50% of both videos and pictures. when copying the link into my browser the videos/pictures display fine. could my VPN create any problems?

**Comment by Amenly** [comment]
Hmm, possibly. Are you able to log into OF normally with your VPN enabled? I do know that at some point (and maybe it's still the case) they had a NordVPN IP blocked for some reason. But it doesn't explain why it downloads some files and not all.

**Comment by Brynting** [comment]
no problem showing media at all when using the browser and the VPN. i did have a problem a few weeks ago with showing media though, but its working fine with the browser now.

**Comment by Brynting** [comment]
trying again now without the VPN

**Comment by Brynting** [comment]
not getting the 403 error anymore but for some users its only getting the header and avatar even though i can se that they have more content posted and even some purchased messages.

**Comment by Amenly** [comment]
It's good that you're not getting 403'd anymore, but the other issue sounds like it's not using the right auth information (a.k.a. your `sess` cookie, `auth_id` value, etc.). Is there any chance you might've logged out and logged in? That will usually reset those values and you'll have to reenter them by editing the `auth.json` file. But now that I think about it, I don't think this is the case because the program should've raised a 400 status code error.

Another possibility is that you already downloaded those files before and now the database file (which is used for preventing files that have been downloaded before from being downloaded again) is doing what it's supposed to do. In the future, I'll add the ability to pass a command line argument that will tell the program to temporarily disable that feature.

**Comment by Brynting** [comment]
if the database file is deleted will a new one be created?

**Comment by Amenly** [comment]
Yeah, a new one will be created.

If you wanted, something you could do is make a copy of the database file and place it in some temporary folder before deleting the original database file. Then, after you rescrape the accounts that have been giving you issues, you could use the migration feature by giving the program a path to that temporary folder (this way you keep what you had before). But it's up to you of course if you want to bother with it.

In case you don't know where it's located, it should be located in your home directory: `~/.config/onlyfans-scraper/models.db`. If you can't find the `.config` folder, you may need to enable the option to view hidden folders (this varies between operating systems).

**Comment by Brynting** [comment]
deleted the database and double checked auth info. everything is working as intended now. seems like the vpn caused the 403 error but the files that failed got added to the database anyways so when i turned of vpn it still wouldn't download.

**Comment by Amenly** [comment]
Well that's good but that's definitely a bug. It should only be adding them to the database if the file finishes being downloaded and is *actually* a file. I'll have to add another safeguard like monitoring download progress then.

**Comment by Brynting** [comment]
Thanks for your help!
