### ISSUE TITLE
Somethink has wrong...

### ISSUE THREAD

**Issue by xagler** [Amenly/onlyfans-scraper#91]
Looks like today onlyfans changed somethink, every request stoped working... Any Ideas to fix?

**Comment by Amenly** [comment]
Everything seems fine for me. Is it good now? If you're getting any 400-level status codes, it means it has something to do with your `auth` info (commonly caused by updating your browser which changes your user agent). Generally speaking, if you see `Status - UP`  when you use the program, it's going to be something on your end 99% of the time.

**Comment by xagler** [comment]
> Everything seems fine for me. Is it good now? If you're getting any 400-level status codes, it means it has something to do with your `auth` info (commonly caused by updating your browser which changes your user agent). Generally speaking, if you see `Status - UP` when you use the program, it's going to be something on your end 99% of the time.

Sorry, it was my mistake ... Everythink work flowless)
